name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run test case
      run: make test

  build-and-publish:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ${{ github.repository }}
      IMAGE_TAG: ${{ github.sha }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: false
        tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        labels: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}